import React from 'react'


export default React.createContext({
    total:[],
    orderDish: [],
    AdminPage:"list",
    user: {},
    dish: [],
    dishId: [],
    table: null,
    orderInfo: null,
    RatingCount: 0,
    RatingId:"",
    changeId: "",
    RatingDish: null,
    Collapse: false,
    CategoryModel: [],
    LiveOrder: [],
    setDishId: id => {},
    deletAlldishId: id =>{},
    addPrice: price =>{},
    deletPrice: index =>{},
    addDish: dish =>{},
    updateDish: dish=>{},
    deleteDish: index =>{},
    deleteAllOrder: d =>{},
    IncCount: (id,count) =>{},
    DecCount: (id,count) =>{},
    Inctotal:(id,total) =>{},
    Dectotal:(id,total) =>{},
    DeleteFirstDish: () =>{},
    setAdminPage: data =>{},
    LoginUser: data =>{},
    getDish: dish =>{},
    deleteAllDish:dish=>{},
    setTable: N =>{},
    setOrderInfo: info =>{},
    DeletTotal: total =>{},
    IncRating: count =>{},
    DecRating: count =>{},
    changeTheId: id =>{},
    setRatingDish: RatingObj =>{},
    setRatingId: id =>{},
    setCollapse: bool =>{},
    setCategoryModel: data =>{},
    setLiveOrder: order =>{}
 })